Repository its-harshil/Hacktoberfest_2021, pull requests merged in 2021-10, with the labels that each got.

#229 Create Insertion sort
  Java/Insertion sort
Labels: hacktoberfest, hacktoberfest-accepted

#228 Create Binary_Search.cpp
  Algorithms/Binary_Search.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#230 Create NonRepeatingNumbers.cpp
  C++/NonRepeatingNumbers.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#233 Java code for Heap Sort Algorithm
  Java/HeapSort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#235 Searching in a sorted and rotated array
  Java/Search in a sorted and rotated array.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#234 Added Snake_and_Fruit.py
  Snake_and_Fruit.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#236 Adding Code to Search An Element in Linked List
  Data Structures/Search An Element
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#231 Create fastExpoentiation.cpp
  C++/fastExpoentiation.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#237 Create quick_sort.py
  quick_sort.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#242 Create Bottom Navigation Bar
  Websites/Bottom Navigation Bar
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#244 add to do list
  TO-DO List/index.html
  TO-DO List/script.js
  TO-DO List/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#245 File to check if a given number is an Armstrong number.
  Check if Armstrong Number
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#247 uploaded a file converter code as mentioned by you in the issue section using java, working is explained in readme file section.
  File-Converter-java/README.md
  File-Converter-java/Test.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#248 To-Do-List
  JavaScript/To-Do-List/To-do-list.html
  JavaScript/To-Do-List/script1.js
  JavaScript/To-Do-List/style1.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#250 Shortest Job Scheduling
  C++/SJS.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#226 Create 404.html
  404.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#249 CPP advance calculator added!
  C++/adv_calc.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#251 rock paper scissors in prolog
  rockpaperscissors.pl
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#257 Day 2 Task Completed : A Quiz App
  A Quiz App/App.html
  A Quiz App/Background.png
  A Quiz App/readme.md
  A Quiz App/script.js
  A Quiz App/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#258 Created new dynamic quiz app
  Quiz-App/function.js
  Quiz-App/index.html
  Quiz-App/questions.js
  Quiz-App/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#255 Desktop-notifier in python hactober2021
  Python/Desktop-notifier-hacktober.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#260 Fetch Covid Data By County
  WebScrapper/covid_scrapper.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#259 DONE: Jarvis virtual assistance generated.
  Speech_Recognition/jarvis_ai_virtual_robo.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#263 Alarm Clock
  Alarm Clock/AlarmClock_Simple.py
  Alarm Clock/Alarm_using_GUI.py
  Alarm Clock/sound.wav
  Alarm Clock/sound1.mp3
  Alarm Clock/sound2.mp3
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#267 Digital Clock GUI in Python3.
  DigitalClock.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#266 Added Currency Converter made in React.js
  JavaScript/currency_converter/.gitignore
  JavaScript/currency_converter/README.md
  JavaScript/currency_converter/package-lock.json
  JavaScript/currency_converter/package.json
  JavaScript/currency_converter/public/favicon.ico
  JavaScript/currency_converter/public/index.html
  JavaScript/currency_converter/public/logo192.png
  JavaScript/currency_converter/public/logo512.png
  JavaScript/currency_converter/public/manifest.json
  JavaScript/currency_converter/public/robots.txt
  JavaScript/currency_converter/src/App.css
  JavaScript/currency_converter/src/App.js
  JavaScript/currency_converter/src/currencyLabel.js
  JavaScript/currency_converter/src/index.css
  JavaScript/currency_converter/src/index.js
  JavaScript/currency_converter/yarn.lock
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#264 Created a Chat For both server & reciever
  Python/chat.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#265 rock_paper_scissor.html
  rock_paper_scissor_game/rock_paper_scissor.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#253 To check whether it's a krishnamurty number or not
  C++/Krishnamurty no.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#252 Add Rotate Array by D position Solution with Documentation
  Java/Left Rotate Array By D Place/Left rotate array by D places documentation.md
  Java/Left Rotate Array By D Place/LeftRotate.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#262 Create armstrong_number.cpp
  C++/armstrong_number.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#270 Uploaded snake game in JS
  snake-gamejs/index.html
  snake-gamejs/script.js
  snake-gamejs/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#274 Adding Python Bulk File Renamer
  bulk-rename-project/requirements.txt
  bulk-rename-project/rprename/__init__.py
  bulk-rename-project/rprename/__pycache__/__init__.cpython-38.pyc
  bulk-rename-project/rprename/__pycache__/app.cpython-38.pyc
  bulk-rename-project/rprename/__pycache__/rename.cpython-38.pyc
  bulk-rename-project/rprename/__pycache__/views.cpython-38.pyc
  bulk-rename-project/rprename/app.py
  bulk-rename-project/rprename/rename.py
  bulk-rename-project/rprename/ui/__pycache__/window.cpython-38.pyc
  bulk-rename-project/rprename/ui/window.py
  bulk-rename-project/rprename/ui/window.ui
  bulk-rename-project/rprename/views.py
  bulk-rename-project/rprenamer.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#273 Created Amazon price tracker
  Amazon_price_tracker/amazon_price_tracker.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#272 Create snakegame.java
  Java/snakegame.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#271 Snake Game in C
  C/Snake_Game.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#275 Build Amazon price tracker (named as Stalker)
  Stalker/README.md
  Stalker/Stalker.py
  Stalker/tempCodeRunnerFile.py
  Stalker/test.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#276 Create DisplayingArrayElements.cpp
  C++/DisplayingArrayElements.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#277 Create array.py
  Python/array.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#278 Create array.java
  Java/array.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#282 Create AlarmClock.java
  Java/AlarmClock.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#284 Create Amazonprice.py
  Python/Amazonprice.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#289 Create testpull
  url_shortener/testpull
Labels: hacktoberfest-accepted
